# Node 22.15.0을 베이스로 사용
FROM node:22.15.0

# 작업 디렉토리 생성
RUN mkdir /code/
WORKDIR /app

# 종속성 설치
COPY package*.json ./
RUN npm install

# 나머지 소스 복사
COPY . .

# 포트 개방 (개발 서버 포트)
EXPOSE 3001

# 개발 서버 실행 (hot reload)
CMD ["npm", "run", "dev"]
